# Parameter header dan skiprows pada read_csv

### Import Modul dan Cek Versi

In [1]:
import pandas as pd

print(pd.__version__)

1.3.5

In [2]:
df = pd.read_csv('/content/Iris_eror.csv')
df.head(8)

    1            5.1           3.5            1.4           0.2   Iris-error
0   2            4.9           3.0            1.4           0.2   Iris-error
1  Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
2   1            5.1           3.5            1.4           0.2  Iris-setosa
3   2            4.9           3.0            1.4           0.2  Iris-setosa
4   3            4.7           3.2            1.3           0.2  Iris-setosa
5   4            4.6           3.1            1.5           0.2  Iris-setosa
6   5            5.0           3.6            1.4           0.2  Iris-setosa
7   6            5.4           3.9            1.7           0.4  Iris-setosa

In [3]:
df = pd.read_csv('/content/Iris_eror.csv', header=2, skiprows=[5,6])
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   5            5.0           3.6            1.4           0.2  Iris-setosa
3   6            5.4           3.9            1.7           0.4  Iris-setosa
4   7            4.6           3.4            1.4           0.3  Iris-setosa